#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/KKISTxT4YBCAnWGcdMbwL6F+eoTBBbQQWCh4Kxis3xJqWodWWm4LJSDAOI3ZzmkhFGw0Vp+12Vm5tV5XbjOIBQgOa3g076eTCPc0gkcF4t0KMiKx4qWlY1fspZWEYFcBH2lM4Od+GVJMZvifTsN+AhEBb/R7z3JenpU5itzxwEredibO4+XVpgS9Ik9s3GqSAVSAatSoU4P87bZjpsMAacYtdnDI8xaT+YrOzDH9mqu/01QMdD4mM1ARy06AxaMGO52joKKNGZSFdinX7VZoGm8TcIyQUKnJQgZIi57lEXCTxbcUM2kbL1pC+ZoHOWXnnoE51W00kgcP+VHMEKGZ aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key # NUY
    ssh_pwauth: false
    disable_root: false
package_update: true
packages:
  - mariadb-server
  - php-mysqli

runcmd:
  - sudo apt update
  - sudo systemctl enable mariadb
  - sudo systemctl start mariadb
  - mysql -e "CREATE USER 'admin'@'%' IDENTIFIED BY 'password';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;"
